# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlHpaStatus < Formula
  desc "kubectl plugin for HPA status, scaling analysis, and suggested fixes"
  homepage "https://github.com/mattsu2020/kubectl-hpa-status"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v0.7.0/kubectl-hpa-status_v0.7.0_darwin_amd64.tar.gz"
      sha256 "79363c3a1afbddda9a3cbc09e5065569c2b31bed07af4e46851dc94a89de9635"

      def install
        bin.install "kubectl-hpa-status"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v0.7.0/kubectl-hpa-status_v0.7.0_darwin_arm64.tar.gz"
      sha256 "df9df4781c17bdaf792cfa339f259d2fb12ee1bca43ed1f31a4b6e98c7313b7f"

      def install
        bin.install "kubectl-hpa-status"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v0.7.0/kubectl-hpa-status_v0.7.0_linux_amd64.tar.gz"
        sha256 "711b5e13f80f2ec2a1087f763efb5857afb3bf06a4ba0ca5c00d4cf467a06663"

        def install
          bin.install "kubectl-hpa-status"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v0.7.0/kubectl-hpa-status_v0.7.0_linux_arm64.tar.gz"
        sha256 "268e75433ac8a7be4d41f7ea30909b2fb035724d0e168fa48eaa509ddf183833"

        def install
          bin.install "kubectl-hpa-status"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Try:
        kubectl-hpa-status list -A --wide
        kubectl-hpa-status status <hpa-name> --suggest
        kubectl-hpa-status status <hpa-name> --keda --explain
        kubectl-hpa-status status <hpa-name> --fix --apply
        kubectl-hpa-status tui
    EOS
  end

  test do
    system "#{bin}/kubectl-hpa-status", "version"
  end
end
