# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlHpaStatus < Formula
  desc "kubectl plugin for HPA status, scaling analysis, and suggested fixes"
  homepage "https://github.com/mattsu2020/kubectl-hpa-status"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v0.5.0/kubectl-hpa-status_v0.5.0_darwin_amd64.tar.gz"
      sha256 "03ce272c01a406dcaf15f66446cb8684bc73f88e2091ea1daa4a8293ad3b9315"

      def install
        bin.install "kubectl-hpa-status"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v0.5.0/kubectl-hpa-status_v0.5.0_darwin_arm64.tar.gz"
      sha256 "c6413056cc1094f9db06a8b5323bb9dd0eb84b8d0cf8e69e7edc3a212ee5dbbb"

      def install
        bin.install "kubectl-hpa-status"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v0.5.0/kubectl-hpa-status_v0.5.0_linux_amd64.tar.gz"
        sha256 "2a80b3e93814e5b5295e23cbc936fb3b63c2d510b0e76a7e4f4a29a39e804f6b"

        def install
          bin.install "kubectl-hpa-status"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v0.5.0/kubectl-hpa-status_v0.5.0_linux_arm64.tar.gz"
        sha256 "e68c4cc95f16e4cb308a54419f803450ffbec2caecede06a23020b24dbb7ba27"

        def install
          bin.install "kubectl-hpa-status"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Try:
        kubectl-hpa-status list -A --wide
        kubectl-hpa-status status <hpa-name> --suggest
        kubectl-hpa-status status <hpa-name> --keda --explain
        kubectl-hpa-status status <hpa-name> --fix --apply
        kubectl-hpa-status tui
    EOS
  end

  test do
    system "#{bin}/kubectl-hpa-status", "version"
  end
end
