# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-hpa-status" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "d9d7f04dd6e63d443140d5f7701e040c80fd7671ddd92b9459be735deff976ad"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "055cc86a8fd062d07f3aff7dae013a44d4b3fd441a14fea705684d99f5c29d24"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1f6f68817d8a5834b6dfdacf4fa4ca77506f7373c8d83f73fac9a482cb942d0f"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e4f02fea4fdd246ee7ca867c695a59c2ef68fb55f6690ec05c0c9ba136b77759"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubectl-hpa-status"
  desc "kubectl plugin for HPA status, scaling analysis, and suggested fixes"
  homepage "https://github.com/mattsu2020/kubectl-hpa-status"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-hpa-status"

  # No zap stanza required

  caveats <<~EOS
    Try:
      kubectl-hpa-status list -A --wide
      kubectl-hpa-status status <hpa-name> --suggest
      kubectl-hpa-status status <hpa-name> --keda --explain
      kubectl-hpa-status status <hpa-name> --fix --apply
      kubectl-hpa-status tui
  EOS
end
