# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-hpa-status" do
  version "3.1.0"

  on_macos do
    on_intel do
      sha256 "38bd2f40ae8a9df63bb4b38d94f7e56516c11c5b673dd9560e695e691b53646c"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "143d4ab6f1bd26856fcbcaa7835cd60434d7e8d70909d020942c34e5c2cfb225"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0686beaa1f42cb9ee4b6ca6744880de50ab5da3049b371b47c973683d854b01"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00555e3c1edc087b2ea87148b71136a4c9974ca278af53d714365c31a1b2d5cd"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubectl-hpa-status"
  desc "kubectl plugin for HPA status, scaling analysis, and suggested fixes"
  homepage "https://github.com/mattsu2020/kubectl-hpa-status"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-hpa-status"

  # No zap stanza required

  caveats <<~EOS
    Try:
      kubectl-hpa-status list -A --wide
      kubectl-hpa-status status <hpa-name> --suggest
      kubectl-hpa-status status <hpa-name> --keda --explain
      kubectl-hpa-status status <hpa-name> --fix --apply
      kubectl-hpa-status tui
  EOS
end
