# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-hpa-status" do
  version "4.0.0"

  on_macos do
    on_intel do
      sha256 "a4728bf65d51faedac2cd3a1eef6e94f20acc83f1c04d570154277a8e8859096"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "774182cf4d6a80d81e114d0229a62be77996056cdb1b0a8f3dcadd71236cdddf"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abdc482eb887a7cd9673cd0189bbdd670317d94cb6474cccb43ab7be1fe3618d"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7da4ee13f5bedf32df8516bb3466bb06dac9c405674501bb8754bec9161bcc68"
      url "https://github.com/mattsu2020/kubectl-hpa-status/releases/download/v#{version}/kubectl-hpa-status_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubectl-hpa-status"
  desc "kubectl plugin for HPA status, scaling analysis, and suggested fixes"
  homepage "https://github.com/mattsu2020/kubectl-hpa-status"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-hpa-status"

  # No zap stanza required

  caveats <<~EOS
    Try:
      kubectl-hpa-status list -A --wide
      kubectl-hpa-status status <hpa-name> --suggest
      kubectl-hpa-status status <hpa-name> --keda --explain
      kubectl-hpa-status status <hpa-name> --fix --apply
      kubectl-hpa-status tui
  EOS
end
